marklogic/marklogic-sesame

marklogic-sesame/build.gradle, marklogic-sesame/src/jmh/java/com/marklogic/semantics/sesame/benchmarks/MarkLogicRepositoryConnectionNaivePerfTest.java, marklogic-sesame/src/jmh/resources/log4j.properties, marklogic-sesame/src/jmh/resources/logback-test.xml, marklogic-sesame/src/jmh/resources/testdata/databases.rdf, marklogic-sesame/src/jmh/resources/testdata/default-graph-1.ttl, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQuery.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java
fixed typo for baseURI handling.
enhanced jhm perf tests.
=> fix for baseURI handling

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java
for when null supplied as a var to ValueFactory createStatement
=> added test for Assertion error

marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQueryTest.java
this passes now, most likely due to commit 42978eec4881fb9e35c9a07c58d694ac1d010020
=> fix for #45

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java
This work fixes issues with hasStatement and covers transactions a little more safely.
=> Issue #126 hasStatement rework

marklogic-sesame/build.gradle, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepository.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicExceptionsTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicGraphPermsTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java
addresses #139, #98, #121 and updates build.gradle
=> several fixes (refactor to use setBaseUri())

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQuery.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicCombinationQueryTest.java
log statement was blowing up constrainingQueryDefinition, easy fix
=> fix for #124

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQueryDependent.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQueryTest.java
query sets SPARQLRuleset varargs eg.
```
tupleQuery.setRulesets(SPARQLRuleset.RDFS_FULL,SPARQLRuleset.DOMAIN);
```
added test to verify
=> fix for #111

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionDependent.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicBooleanQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicUpdateQuery.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicCombinationQueryTest.java
this adds ability to set a default Constraining Query on the connection ala
```
conn.setDefaultQueryDef(stringDef);
```
=> fix for enhancement #142

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionDependent.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicBooleanQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicUpdateQuery.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicCombinationQueryTest.java
Reverts marklogic/marklogic-sesame#162
=> Revert "fix for enhancement #142"

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java
my bad when I applied fix the first time
=> reapply of fix #108, on the right logic branch

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicExceptionsTest.java
when no txid exists and conn.commit() is applied this now throws MarkLogicTransactionException.
=> fix for #174

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryWriteCacheTest.java
added sync() where required, minor fixes supporting write cache all tests green
=> Issue 140c

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionDependent.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicBooleanQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicQueryDependent.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicUpdateQuery.java
just adds support for setting multiple graph perms
=> fix for #185

marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicGraphPermsTest.java
=> amend test for #185

marklogic-sesame-examples/src/main/java/com/marklogic/semantics/sesame/examples/Example2_Advanced.java, marklogic-sesame-examples/src/main/resources/logback.xml, marklogic-sesame/README.md, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionDependent.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicBackgroundGraphResult.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/package-info.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/config/package-info.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/package-info.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicExceptionsTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicGraphPermsTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryTransactionTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryWriteCacheTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/SesameTestBase.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/config/MarkLogicRepositoryFactoryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicBooleanQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicCombinationQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicUpdateQueryTest.java
enhanced examples, fixed unit test reader connection and other minor fixes.
=> Minor fixes

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryWriteCacheTest.java
graph operations honor txid now, enabled write cache and attendant tests all green.
=> fix for #183

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java
missed off new sync() call on remove.
=> fix for #133

README.md
done with edits to README as per @jmckean17 review.
=> added links to README

marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryWriteCacheTest.java
simplified test verifying write cache works properly with size().
=> new test for issue 140

marklogic-sesame-functionaltests/src/test/resources/logback-test.xml
=> added logback for more debugging of functional tests

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java
fix for change https://github.com/marklogic/java-client-api/issues/362 in java api client.
=> fix for java api client change for RDFTypes

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java
ensure to unset with empty graph perms
=> add enhancements for init GraphPerms with empty()

marklogic-sesame-performance/build.gradle, marklogic-sesame/build.gradle
I've been running 2.8.6 for a few weeks now, all tests green.
=> bump to latest Sesame stable v2.8.6

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepository.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/config/MarkLogicRepositoryConfig.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/config/MarkLogicRepositoryFactory.java, marklogic-sesame/src/main/resources/META-INF/services/org.openrdf.repository.config.RepositoryFactory, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/config/MarkLogicRepositoryFactoryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/config/MarkLogicRepositoryManagerTest.java
=> enable usage with LocalRepositoryManager

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/package-info.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/config/package-info.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/overview.html, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/package-info.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/package-info.java
as per @jmckean17 10/07 review.
=> amended javadocs

marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/config/MarkLogicRepositoryManagerTest.java
=> make unit test generic

README.md
=> minor readme amends

marklogic-sesame/gradle.properties
will keep this as SNAPSHOT until we release
=> add back SNAPSHOT to develop branch

marklogic-sesame/build.gradle, marklogic-sesame/gradle.properties
=> enable maven publishing

README.md
=> update README for support Sesame 2.8.7

marklogic-sesame-examples/build.gradle, marklogic-sesame-performance/build.gradle, marklogic-sesame/build.gradle
ml-gradle is now in gradle plugins, pulling from there.
"gradle.plugin.com.marklogic:ml-gradle:2.0rc5"
=> upgrade ml-gradle

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryWriteCacheTest.java
=> make write cache threadsafe, #241

marklogic-sesame-examples/README.md, marklogic-sesame-examples/build.gradle
added triple loading example to example subproject.
=> enhanced examples with triple loading ex.

marklogic-sesame-examples/src/main/java/com/marklogic/semantics/sesame/examples/Example4_Load_Triples.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionDependent.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/overview.html, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryWriteCacheTest.java
this patch adds the ability to configure writeCache params.
=> expose write cache parameters

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionDependent.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicSesameException.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicTransactionException.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicUpdateQuery.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryWriteCacheTest.java
* addresses some sonar suggestions #235 
* force sync() of write cache when performing size query
* minor amends
=> sonar suggestions, minor amends

README.md, marklogic-sesame/build.gradle, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQuery.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java
=> prep for release

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java
=> remove initTimer from connection constructor

marklogic-sesame-functionaltests/src/test/java/com/marklogic/sesame/functionaltests/MarkLogicRepositoryConnectionTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MultiThreadedPersistenceTest.java
=> 1.0 develop

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MultiThreadedPersistenceTest.java
there was some reformatting when I did this PR, hence the large
* inclusion of explicit close on databaseClient
* removal of synchronized on flush method for WriteCacheTimer
* updated multithreaded test
=> bug:41543 and issue #287

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java
bumped start delay on write cache
=> bug:41543 and issue #287, tweak starting delay for write cache

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java
=> bug:41543 and issue #287, reorder close

marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MultiThreadedPersistenceTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/SesameTestBase.java
minor cleanup for the tests themselves
=> ensure tests release any java api client connections

marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicCombinationQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQueryTest.java
amend tests to explicit close query results.
=> add result.close() to tests

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/overview.html, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicGraphQuery.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQuery.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicExceptionsTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/SesameTestBase.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQueryTest.java
minor tweaks to tests and code
=> minor optimisations

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/WriteCacheTimerTask.java
=> remove synchronized from add WriteCache

marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MultiThreadedPersistenceTest.java
disable 2 tests until new java api client
=> ignore some tests until new java api client

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/SesameTestBase.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQueryTest.java
=> #326 copy options from struc query to sparqlquerydefinition

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnection.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/TripleCache.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MultiThreadedPersistenceTest.java
Reverts marklogic/marklogic-sesame#329
=> Revert "add begin/commit to multithreaded test,add some sync keywords"

README.md, marklogic-sesame-examples/build.gradle, marklogic-sesame-examples/gradle.properties, marklogic-sesame-performance/build.gradle, marklogic-sesame-performance/gradle.properties, marklogic-sesame/gradle.properties, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClient.java, marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/MarkLogicClientImpl.java
=> bump version number for soon to be release, inject some log statements

marklogic-sesame/src/main/java/com/marklogic/semantics/sesame/client/TripleWriteCache.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/MarkLogicRepositoryConnectionTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicBooleanQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicTupleQueryTest.java, marklogic-sesame/src/test/java/com/marklogic/semantics/sesame/query/MarkLogicUpdateQueryTest.java
ensure skolomize of bnodes in write cache.
added some more unit tests.
=> enhance write cache
